# Generated by Django 6.0.5 on 2026-06-04 04:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
